import turtle

turtle.showturtle()
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.penup()
turtle.goto(100,0)
turtle.pendown()
turtle.forward(200)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.exitonclick()
